name: PHP Syntax

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check PHP syntax
      shell: bash
      run: |
        php --version
        while IFS= read -r -d '' file; do
          php -l "$file"
        done < <(git ls-files -z -- '*.php')
